name: deploy_frontend

on:
  workflow_call:
    secrets:
      EC2_FRONTEND_HOST:
        required: true
      EC2_FRONTEND_SSH_KEY:
        required: true
      NEXT_PUBLIC_API_URL:
        required: true
      NEXT_PUBLIC_RECAPTCHA_SITE_KEY:
        required: true
      NEXT_PUBLIC_EMAIL_GATEWAY_HANDLER_URL:
        required: true
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: deploy-frontend
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # defaults:
    #   run:
    #     working-directory: tandartspraktijk-hengelo

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build Nextjs.app
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE_KEY }}
          NEXT_PUBLIC_EMAIL_GATEWAY_HANDLER_URL: ${{ secrets.NEXT_PUBLIC_EMAIL_GATEWAY_HANDLER_URL }}
          NODE_ENV: production
        run: npm run build

      - name: Deploy with rsync
        uses: Burnett01/rsync-deployments@7.1.0
        with:
          switches: -avzr --delete
          path: ".next public package.json package-lock.json next.config.mjs .npmrc"
          remote_path: "/swiftymo-website"
          remote_host: ${{ secrets.EC2_FRONTEND_HOST }}
          remote_user: ubuntu
          remote_key: ${{ secrets.EC2_FRONTEND_SSH_KEY }}

      - name: Install server deps & restart service
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_FRONTEND_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_FRONTEND_SSH_KEY }}
          script: |
            set -e
            # Use nvm to load Node.js
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 20 || nvm use node

            cd /swiftymo-website
            npm ci

            sudo -n systemctl restart swiftymo-website.service
